'use client';
import { useEffect,useState } from 'react'; import { useRouter } from 'next/navigation';
import CameraCapture from '@/components/CameraCapture'; import { Search,ShieldCheck,UserRound,ArrowLeft,Radar } from 'lucide-react';
import { useFCRSounds } from '@/components/SoundSystem'; import { WorldMap } from '@/components/FCRVisuals';
const steps=['Uploading subject data','Analyzing facial structure','Checking fictional database','Scanning social behavior','Calculating biryani addiction','Finding criminal activities','Finalizing results'];
export default function ScanPage(){
 const router=useRouter(); const {startAmbient,playFCRSound}=useFCRSounds(); const [stage,setStage]=useState<1|2|3>(1); const [name,setName]=useState(''); const [running,setRunning]=useState(false); const [pct,setPct]=useState(0); const [step,setStep]=useState(0);
 const continueToCamera=()=>{if(!name.trim())return;startAmbient();playFCRSound('confirm');setStage(2)};
 useEffect(()=>{if(!running)return;playFCRSound('scan');const timer=window.setInterval(()=>setPct(v=>{const next=Math.min(v+7,100);setStep(Math.min(Math.floor(next/15),steps.length-1));if(next>=100){window.clearInterval(timer);playFCRSound('complete');window.setTimeout(()=>router.push('/result'),850)}return next}),520);return()=>window.clearInterval(timer)},[running,router,playFCRSound]);
 const captured=(data:string)=>{playFCRSound('confirm');localStorage.setItem('fcr_photo',data);localStorage.setItem('fcr_name',name.trim());setStage(3);setRunning(true);setPct(3);setStep(0)};
 if(stage===1)return <main className="app scan-page"><section className="shell"><div className="glass"><header className="topbar"><button className="icon-btn" onClick={()=>router.push('/')}><ArrowLeft size={18}/></button><strong className="logo-mark">F<span>CR</span></strong><span className="badge">STEP 1 OF 3</span></header><div className="content"><div className="stepbar"><i className="active"/><i/><i/></div><div className="hero compact"><div className="step-icon"><UserRound size={27}/></div><div className="eyebrow">SUBJECT REGISTRATION</div><h1 className="screen-title">WHO'S UNDER<br/>INVESTIGATION?</h1><p className="sub">Enter your friend's name or nickname.</p></div><input autoFocus className="input name-input" value={name} onChange={e=>setName(e.target.value)} maxLength={40} placeholder="e.g. Rakib, Rifat, Pola..."/><button className="primary hero-cta" onClick={continueToCamera} disabled={!name.trim()}>CONTINUE <span>→</span></button><div className="quote">“Good friends.<br/><b>Bad records.</b> 😎”</div></div></div></section></main>;
 if(stage===2)return <main className="app scan-page"><section className="shell"><div className="glass"><header className="topbar"><button className="icon-btn" onClick={()=>setStage(1)}><ArrowLeft size={18}/></button><strong className="logo-mark">F<span>CR</span></strong><span className="badge">STEP 2 OF 3</span></header><div className="content"><div className="stepbar"><i className="done"/><i className="active"/><i/></div><div className="hero compact"><div className="eyebrow">SUBJECT VERIFICATION</div><h1 className="screen-title">TAKE A<br/>PHOTO</h1><p className="sub">Position your friend's face inside the frame.</p></div><CameraCapture onCaptured={captured}/></div></div></section></main>;
 return <main className="app scan-page investigation"><div className="investigation-glow"/><section className="shell"><div className="glass"><header className="topbar"><strong className="logo-mark">F<span>CR</span></strong><span className="badge"><Search size={14}/> STEP 3 OF 3</span></header><div className="content"><div className="stepbar"><i className="done"/><i className="done"/><i className="active"/></div><div className="hero compact"><div className="eyebrow">GLOBAL FRIEND INTELLIGENCE NETWORK</div><h1 className="screen-title">INVESTIGATING<span className="blink">...</span></h1><p className="sub">Accessing fictional case database...</p></div><div className="world-map"><WorldMap/><div className="radar-core"><Radar size={24}/></div><div className="map-scanline"/></div><div className="progress"><div style={{width:pct+'%'}}/></div><div className="row progress-label"><span className="label">INVESTIGATION PROGRESS</span><span className="value">{pct}%</span></div><div className="stack investigation-list">{steps.map((s,i)=><div key={s} className="row"><span className={i<step?'check done-text':i===step?'check running-text':'check'}>{i<step?'✓':i===step?'●':'○'}</span><span className="label" style={{flex:1}}>{s}</span><span className="status">{i<step?'DONE':i===step?'RUNNING':'WAIT'}</span></div>)}</div><div className="disclaimer"><ShieldCheck size={15}/> Fictional analysis only. No biometric identification is performed.</div></div></div></section></main>;
}